#!/bin/sh
#
# name     : install-tmuxen, tmuxen install script
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 02
# modified : 2013 Jul 06
#

bin=$HOME/bin
cwd=$(cd $(dirname $0) && pwd)

[ -d $bin ] || mkdir $bin

echo "Installing tmuxen to $bin"
ln -sf $cwd/tmuxen $bin/tmuxen
ln -sf $cwd/sysinfo $bin/sysinfo

echo "Symlinking _tmux.conf to $HOME/.tmux.conf"
[ -f $HOME/.tmux.conf ] && mv $HOME/.tmux.conf $HOME/.tmux.conf.bk-$(date '+%Y%m%d%H%M%S')
ln -sf $cwd/_tmux.conf $HOME/.tmux.conf
[ -f $HOME/.vimrc ] || ln -s $cwd/vimrc $HOME/.vimrc

exit
