#!/bin/sh
#
# name     : install-tmuxen, tmuxen install script
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 02
# modified : 2013 Jul 06
#

bin=/usr/local/bin
cwd=$(cd $(dirname $0) && pwd)
[ -f /usr/bin/tmux ] || yum -y localinstall $cwd/pkgs/*.rpm
[ -d $bin ] || mkdir $bin

echo "Installing tmuxen to $bin"
/bin/cp -f $cwd/tmuxen $bin/tmuxen
/bin/cp -f $cwd/sysinfo $bin/sysinfo

echo "Updateing $HOME/.tmux.conf"
[ -f $HOME/.tmux.conf ] && mv $HOME/.tmux.conf $HOME/.tmux.conf.bk-$(date '+%Y%m%d%H%M%S')
/bin/cp -f $cwd/_tmux.conf $HOME/.tmux.conf
echo "Updateing $HOME/.vimrc and bashrc"
[ -f $HOME/.vimrc ] || /bin/cp -f $cwd/vimrc $HOME/.vimrc
grep -q 'vim' $HOME/.bashrc || echo "alias vi='vim'" >>$HOME/.bashrc

exit
